### ISSUE TITLE
Ghost A.I and full auto main cannon. 

### ISSUE THREAD

**Issue by Mariusstad** [Seb105/Arma-CommanderTurretOverride#4]
During the testing of this mod for the unit I'm part of we had some promising results, the turret override worked just fine with the tanks we tested, until we tested the Abrams. At first it seemed okay, but then the gunner got glitched and could fire the cannon at full-auto, and lost control over his character and an invisible ghost A.I took control over him. He could not do anything except fire his pistol and look around, and if he got killed, couldn't respawn. Very funky

**Comment by Seb105** [comment]
This'll be fixed by default when Arma 2.08 comes out, but that won't be for some time. Right now the mod works by creating an AI and making that unit look at the target, however this seems to fail sometimes.

Until then, there is a lot of reports about issues with the Abrams, I will look into this some more.

Was this the RHS or CUP abrams?

**Comment by Mariusstad** [comment]
It happened with the RHS M1A1AIM

**Comment by Seb105** [comment]
Alright thanks. I've had an idea to make this more reliable, I'll push an update shortly to attempt to fix it.

**Comment by Seb105** [comment]
I have pushed an update. Let me know if this works for you. It won't be perfect until the Arma platform 2.07/2.08 platform update, as it contains a new command that is much more reliable.

**Comment by 20XCharlie1210** [comment]
Hi,

Just now, with a friend on a self-hosted MP server, we encountered this exact issue. So far we've noticed that even if the gunner locks control, the AI will continue to engage and when unlocked, the commander can not slew the gunner's turret until the enemy being engaged is destroyed.

Further, when this happens, as above the player no longer has control of their unit and must re-log. This will create a clone AI in the mission.

Vehicles tested: Merkava, Merkava LIC, T100, T14, T14K, AMV Marshall, FV720 Mora, Pandur, Otokar Arma, Rooikat, Rooikat UP, Leopard 2SG, and BMT2T. Apologies for the differences in names - we tested using ACE.

We had issues with ALL IFV's and APC's with 30-40mm cannons, and also had an issue with the T14, and Rooikat. (Non-K and UP, respectively)
After some time, the gunner was not able to switch ammo states, and if he tried to fire a round, the animation would show but no rounds would impact. Relogging OCCASIONALLY fixed this issue.

Mods:
@ace
@cba_a3
@ACEX
@Commander Turret Override

Thanks!

**Comment by 20XCharlie1210** [comment]
Update: My friend had the idea to rebind the key from alt+T since it had something to do with 'Target' commands for the AI, and it worked for a bit - but after a while, the game would recognise us as 'AI' per se and would revert back to firing without player input, and at times, kicking us out of the vehicle. We tested this with the Rooikat and the Badger IFV. Same mods as above

**Comment by AstralEUD** [comment]
I had this bug with Merkava MBT

**Comment by Seb105** [comment]
I have created V2 of this mod, it requries Version 2.08 as it requires a new scripting command that is getting added, I will update the mod as soon as the game updates. It uses a completely different method to achieve the turret override so shoud fix everything.

**Comment by AstralEUD** [comment]
It's time to update!
